os:
  - linux

language: go

go:
  - 1.11.x

services:
  - docker

env:
  global:
    - GO111MODULE=on
    - GOTFLAGS="-race"
    - IPFS_PATH=/tmp/ipfs
  matrix:
    - BUILD_DEPTYPE=gomod

before_install:
  - docker pull ipfs/go-ipfs:master
  - mkdir /tmp/ipfs && chmod 0777 /tmp/ipfs
  - docker run -d -v /tmp/ipfs:/data/ipfs -p 8080:8080 -p 4001:4001 -p 5001:5001 ipfs/go-ipfs:master "daemon" "--enable-namesys-pubsub"
  
install:
  - go mod download

before_script:
  - go vet ./...

script:
  - go get -d github.com/cheekybits/is/... # remove with gx
  - bash <(curl -s https://raw.githubusercontent.com/ipfs/ci-helpers/master/travis-ci/run-standard-tests.sh)


cache:
  directories:
    - $GOPATH/src/gx
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build

notifications:
  email: false
