name: installipfs
description: install go-ipfs

runs:
  using: "composite"
  steps:
    - name: Install go-ipfs
      shell: bash
      run: |
        cd /tmp    && git clone https://github.com/coryschwartz/go-ipfs.git
        cd go-ipfs && git checkout 153697d524f449ee9bec97245b0fcd7ebc2e8170
        go install ./cmd/ipfs
    - name: Initialize go-ipfs
      shell: bash
      run: (ipfs init)
    - name: Run go-ipfs
      shell: bash
      run: (ipfs daemon --enable-pubsub-experiment &)
